name: live_score
description: Live score app

publish_to: "none"

version: 1.0.0+3

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  bloc: ^8.1.0
  cupertino_icons: ^1.0.5
  dartz: ^0.10.1
  dio: ^5.3.3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  fluttertoast: ^8.2.2
  get_it: ^7.2.0
  hexcolor: ^3.0.1
  internet_connection_checker: ^1.0.0+1
  intl: ^0.18.1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/no_matches.png
    - assets/images/no_stats.png
    - assets/images/Football_playground.png
    - assets/images/substitute.jpg
